// RefGen: writes docs/reference/api/*.rst from IronstrikeApi.dll and IronstrikeApi.xml.
//
//   dotnet run --project docs/tools/RefGen -- <IronstrikeApi.dll> <out dir> [assembly search dirs...]
//
// The XML file is the DLL's sibling (GenerateDocumentationFile). Signatures come from the DLL itself,
// read with MetadataLoadContext; the prose comes from the /// comments. Every public type and member
// must have a <summary>, or this exits with code 1 and lists what is missing.
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;

static class Program
{
    static readonly Dictionary<string, XElement> docs = new();
    static readonly List<string> missing = new();

    static int Main(string[] args)
    {
        if (args.Length < 2) { Console.Error.WriteLine("usage: RefGen <dll> <outdir> [search dirs...]"); return 2; }
        string dll = Path.GetFullPath(args[0]), outDir = args[1];
        string xml = Path.ChangeExtension(dll, ".xml");
        if (!File.Exists(xml)) { Console.Error.WriteLine($"no XML doc file at {xml}"); return 2; }

        foreach (var m in XDocument.Load(xml).Descendants("member"))
            docs[(string)m.Attribute("name")] = m;

        // Every assembly the API's signatures can mention: the runtime, the game's interop set, BepInEx.
        var paths = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        void AddDir(string d)
        {
            if (!Directory.Exists(d)) return;
            foreach (var f in Directory.EnumerateFiles(d, "*.dll", SearchOption.AllDirectories))
                paths.TryAdd(Path.GetFileNameWithoutExtension(f), f);
        }
        AddDir(Path.GetDirectoryName(dll));
        AddDir(Path.GetDirectoryName(typeof(object).Assembly.Location));
        foreach (var d in args.Skip(2)) AddDir(d);
        paths[Path.GetFileNameWithoutExtension(dll)] = dll;

        using var mlc = new MetadataLoadContext(new PathAssemblyResolver(paths.Values));
        var asm = mlc.LoadFromAssemblyPath(dll);

        var types = asm.GetExportedTypes()
            .Where(t => !t.IsNested)
            .OrderBy(t => t.Namespace).ThenBy(t => t.Name)
            .ToList();

        Directory.CreateDirectory(outDir);
        foreach (var f in Directory.EnumerateFiles(outDir, "*.rst")) File.Delete(f);

        var index = new StringBuilder();
        index.AppendLine(".. This file is generated by docs/tools/RefGen. Do not edit.");
        index.AppendLine();
        index.AppendLine("Types by namespace");
        index.AppendLine("==================");
        index.AppendLine();
        index.AppendLine("Every public type in ``IronstrikeApi.dll``, generated from the assembly and its");
        index.AppendLine("documentation comments.");
        index.AppendLine();

        foreach (var g in types.GroupBy(t => t.Namespace))
        {
            index.AppendLine(Heading(g.Key, '-'));
            index.AppendLine(".. list-table::");
            index.AppendLine("   :widths: 30 70");
            index.AppendLine();
            foreach (var t in g)
            {
                index.AppendLine($"   * - :cs:type:`~{t.FullName}`");
                index.AppendLine($"     - {OneLine(Summary(Id(t)))}");
            }
            index.AppendLine();
            index.AppendLine(".. toctree::");
            index.AppendLine("   :hidden:");
            index.AppendLine();
            foreach (var t in g) index.AppendLine($"   {t.FullName}");
            index.AppendLine();

            foreach (var t in g)
                File.WriteAllText(Path.Combine(outDir, t.FullName + ".rst"), TypePage(t));
        }
        File.WriteAllText(Path.Combine(outDir, "index.rst"), index.ToString());

        Console.WriteLine($"RefGen: {types.Count} types -> {outDir}");
        if (missing.Count > 0)
        {
            Console.Error.WriteLine($"RefGen: {missing.Count} public member(s) without a <summary>:");
            foreach (var m in missing) Console.Error.WriteLine("  " + m);
            return 1;
        }
        return 0;
    }

    // ------------------------------------------------------------------ pages

    static string TypePage(Type t)
    {
        var sb = new StringBuilder();
        sb.AppendLine(".. This file is generated by docs/tools/RefGen. Do not edit.");
        sb.AppendLine();
        sb.AppendLine(Heading($"{Esc(TypeName(t))} {Kind(t)}", '='));
        sb.AppendLine($".. cs:namespace:: {t.Namespace}");
        sb.AppendLine();
        WriteType(sb, t, "");
        return sb.ToString();
    }

    static void WriteType(StringBuilder sb, Type t, string ind)
    {
        string id = Id(t);
        sb.AppendLine($"{ind}.. cs:{Kind(t)}:: {TypeSignature(t)}");
        sb.AppendLine($"{ind}   :fullname: {Full(t)}");
        sb.AppendLine();
        Body(sb, id, ind + "   ", null);

        string mi = ind + "   ";
        const BindingFlags F = BindingFlags.Public | BindingFlags.Static | BindingFlags.Instance | BindingFlags.DeclaredOnly;

        if (t.IsEnum)
        {
            foreach (var f in t.GetFields(BindingFlags.Public | BindingFlags.Static))
            {
                sb.AppendLine($"{mi}.. cs:field:: {f.Name} = {Convert.ToInt64(f.GetRawConstantValue())}");
                sb.AppendLine($"{mi}   :fullname: {Full(t)}.{f.Name}");
                sb.AppendLine();
                Body(sb, "F:" + DocName(t) + "." + f.Name, mi + "   ", null);
            }
            return;
        }
        if (IsDelegate(t)) return;

        foreach (var c in t.GetConstructors(BindingFlags.Public | BindingFlags.Instance))
        {
            if (t.IsAbstract && t.IsSealed) break;
            string cid = "M:" + DocName(t) + ".#ctor" + Params(c.GetParameters());
            if (c.GetParameters().Length == 0 && !docs.ContainsKey(cid)) continue;   // implicit default ctor
            sb.AppendLine($"{mi}.. cs:method:: {TypeName(t).Split('<')[0]}({ParamList(c.GetParameters())})");
            sb.AppendLine($"{mi}   :fullname: {Full(t)}.#ctor");
            sb.AppendLine();
            Body(sb, cid, mi + "   ", c.GetParameters());
        }

        foreach (var f in t.GetFields(F).Where(f => !f.IsSpecialName).OrderBy(f => f.Name))
        {
            if (t.GetEvents(F).Any(e => e.Name == f.Name)) continue;
            string mods = f.IsLiteral ? "const " : (f.IsStatic ? "static " : "") + (f.IsInitOnly ? "readonly " : "");
            string val = f.IsLiteral ? " = " + Literal(f.GetRawConstantValue()) : "";
            sb.AppendLine($"{mi}.. cs:field:: public {mods}{TypeName(f.FieldType)} {f.Name}{val}");
            sb.AppendLine($"{mi}   :fullname: {Full(t)}.{f.Name}");
            sb.AppendLine();
            Body(sb, "F:" + DocName(t) + "." + f.Name, mi + "   ", null);
        }

        foreach (var p in t.GetProperties(F).OrderBy(p => p.Name))
        {
            var get = p.GetMethod != null && p.GetMethod.IsPublic ? p.GetMethod : null;
            var set = p.SetMethod != null && p.SetMethod.IsPublic ? p.SetMethod : null;
            if (get == null && set == null) continue;
            bool st = (get ?? set).IsStatic;
            string acc = "{ " + (get != null ? "get; " : "") + (set != null ? "set; " : "") + "}";
            sb.AppendLine($"{mi}.. cs:property:: public {(st ? "static " : "")}{TypeName(p.PropertyType)} {p.Name} {acc}");
            sb.AppendLine($"{mi}   :fullname: {Full(t)}.{p.Name}");
            sb.AppendLine();
            Body(sb, "P:" + DocName(t) + "." + p.Name, mi + "   ", null);
        }

        foreach (var e in t.GetEvents(F).OrderBy(e => e.Name))
        {
            bool st = e.AddMethod?.IsStatic ?? false;
            sb.AppendLine($"{mi}.. cs:event:: public {(st ? "static " : "")}event {TypeName(e.EventHandlerType)} {e.Name}");
            sb.AppendLine($"{mi}   :fullname: {Full(t)}.{e.Name}");
            sb.AppendLine();
            Body(sb, "E:" + DocName(t) + "." + e.Name, mi + "   ", null);
        }

        foreach (var m in t.GetMethods(F).Where(m => !m.IsSpecialName).OrderBy(m => m.Name).ThenBy(m => m.GetParameters().Length))
        {
            // Overrides (ToString and friends) are listed only when they carry their own summary.
            bool isOverride = m.IsVirtual && (m.Attributes & MethodAttributes.NewSlot) == 0;
            if (isOverride && !(docs.TryGetValue(MethodId(t, m), out var od) && od.Element("summary") != null)) continue;
            string mods = isOverride ? "override " : m.IsStatic ? "static " : m.IsAbstract ? "abstract " : m.IsVirtual && !m.IsFinal ? "virtual " : "";
            sb.AppendLine($"{mi}.. cs:method:: public {mods}{TypeName(m.ReturnType)} {m.Name}({ParamList(m.GetParameters())})");
            sb.AppendLine($"{mi}   :fullname: {Full(t)}.{m.Name}");
            sb.AppendLine();
            Body(sb, MethodId(t, m), mi + "   ", m.GetParameters());
        }

        foreach (var n in t.GetNestedTypes(BindingFlags.Public).OrderBy(n => n.Name))
            WriteType(sb, n, mi);
    }

    static string MethodId(Type t, MethodInfo m) => "M:" + DocName(t) + "." + m.Name + Params(m.GetParameters());

    static void Body(StringBuilder sb, string id, string ind, ParameterInfo[] ps)
    {
        if (!docs.TryGetValue(id, out var x))
        {
            missing.Add(id);
            sb.AppendLine(ind + "*Undocumented.*");
            sb.AppendLine();
            return;
        }
        if (x.Element("inheritdoc") != null && x.Element("summary") == null) return;
        var summary = x.Element("summary");
        if (summary == null) { missing.Add(id); return; }

        Block(sb, Rst(summary), ind);
        foreach (var r in x.Elements("remarks")) Block(sb, Rst(r), ind);

        var pars = x.Elements("param").ToList();
        if (pars.Count > 0)
        {
            foreach (var p in pars)
                sb.AppendLine($"{ind}:param {(string)p.Attribute("name")}: {OneLine(Rst(p))}");
            sb.AppendLine();
        }
        var ret = x.Element("returns");
        if (ret != null) { sb.AppendLine($"{ind}:returns: {OneLine(Rst(ret))}"); sb.AppendLine(); }
    }

    static void Block(StringBuilder sb, string text, string ind)
    {
        foreach (var line in text.Split('\n')) sb.AppendLine(line.Length == 0 ? "" : ind + line);
        sb.AppendLine();
    }

    // ------------------------------------------------------------------ XML doc -> reST

    static string Summary(string id) => docs.TryGetValue(id, out var x) && x.Element("summary") != null ? Rst(x.Element("summary")) : "";

    static string Rst(XElement e)
    {
        var sb = new StringBuilder();
        Inline(sb, e);
        // Normalise: collapse runs of spaces inside lines, keep blank-line paragraph breaks.
        var paras = Regex.Split(sb.ToString(), @"\n\s*\n")
            .Select(p => p.Contains("\u0001") ? p.Replace("\u0001", "") : Regex.Replace(p.Trim(), @"[ \t]*\n[ \t]*", " "))
            .Select(p => p.Contains("\n  ") ? p : Regex.Replace(p, @" {2,}", " "))
            .Where(p => p.Trim().Length > 0);
        var text = string.Join("\n\n", paras).Trim('\n');
        // Inline markup was padded with spaces so it always parses; pull punctuation back against it.
        text = Regex.Replace(text, @"(``|\*|`) ([.,;:!?)'])", "$1$2");
        text = Regex.Replace(text, @"\( (?=[`*:])", "(");
        return text;
    }

    static void Inline(StringBuilder sb, XElement e)
    {
        foreach (var n in e.Nodes())
        {
            if (n is XText tx) { sb.Append(Esc(tx.Value)); continue; }
            if (n is not XElement el) continue;
            switch (el.Name.LocalName)
            {
                case "c": sb.Append(" ``").Append(el.Value.Trim()).Append("`` "); break;
                case "paramref": case "typeparamref": sb.Append(" *").Append((string)el.Attribute("name")).Append("* "); break;
                case "see":
                    var cref = (string)el.Attribute("cref");
                    if (cref != null) sb.Append(" ").Append(Xref(cref)).Append(" ");
                    else sb.Append(" ``").Append((string)el.Attribute("langword")).Append("`` ");
                    break;
                case "para": sb.Append("\n\n"); Inline(sb, el); sb.Append("\n\n"); break;
                case "code":
                    var lines = el.Value.Replace("\r", "").Trim('\n').Split('\n');
                    int indent = lines.Where(l => l.Trim().Length > 0).Select(l => l.Length - l.TrimStart().Length).DefaultIfEmpty(0).Min();
                    sb.Append("\n\n\u0001.. code-block:: csharp\n\n");
                    foreach (var l in lines) sb.Append("    ").Append(l.Length >= indent ? l.Substring(indent) : l.TrimStart()).Append('\n');
                    sb.Append("\n\n");
                    break;
                default: Inline(sb, el); break;
            }
        }
    }

    static string Xref(string cref)
    {
        string kind = cref.Length > 2 && cref[1] == ':' ? cref.Substring(0, 1) : "T";
        string target = cref.Length > 2 && cref[1] == ':' ? cref.Substring(2) : cref;
        int paren = target.IndexOf('(');
        if (paren >= 0) target = target.Substring(0, paren);
        string role = kind switch { "M" => "meth", "P" => "prop", "F" => "field", "E" => "event", _ => "type" };
        return $":cs:{role}:`~{target}`";
    }

    // Escape what reST would read as markup inside plain prose.
    static string Esc(string s) => Regex.Replace(s ?? "", @"([\\*`|_])", @"\$1");

    static string OneLine(string s) => Regex.Replace(s ?? "", @"\s*\n\s*", " ").Trim();

    static string Heading(string s, char c) => s + "\n" + new string(c, Math.Max(3, s.Length)) + "\n";

    // ------------------------------------------------------------------ signatures

    static bool IsDelegate(Type t) => t.BaseType?.FullName == "System.MulticastDelegate";

    static string Kind(Type t) =>
        t.IsEnum ? "enum" : IsDelegate(t) ? "delegate" : t.IsValueType ? "struct" : t.IsInterface ? "interface" : "class";

    static string TypeSignature(Type t)
    {
        if (IsDelegate(t))
        {
            var inv = t.GetMethod("Invoke");
            return $"public delegate {TypeName(inv.ReturnType)} {t.Name}({ParamList(inv.GetParameters())})";
        }
        string mods = t.IsEnum || t.IsValueType || t.IsInterface ? "" : t.IsAbstract && t.IsSealed ? "static " : t.IsSealed ? "sealed " : t.IsAbstract ? "abstract " : "";
        string bas = "";
        if (!t.IsEnum && !t.IsValueType && t.BaseType != null && t.BaseType.FullName != "System.Object") bas = " : " + TypeName(t.BaseType);
        return $"public {mods}{Kind(t)} {TypeName(t)}{bas}";
    }

    static string Full(Type t) => (t.FullName ?? t.Name).Replace('+', '.');

    static readonly Dictionary<string, string> Builtin = new()
    {
        ["System.Void"] = "void", ["System.Boolean"] = "bool", ["System.Int32"] = "int", ["System.Int64"] = "long",
        ["System.Single"] = "float", ["System.Double"] = "double", ["System.String"] = "string", ["System.Object"] = "object",
        ["System.Byte"] = "byte", ["System.UInt32"] = "uint",
    };

    static string TypeName(Type t)
    {
        if (t.IsByRef) return "ref " + TypeName(t.GetElementType());
        if (t.IsArray) return TypeName(t.GetElementType()) + "[]";
        if (t.IsGenericParameter) return t.Name;
        if (t.FullName != null && Builtin.TryGetValue(t.FullName, out var b)) return b;
        if (t.IsGenericType)
        {
            var def = t.GetGenericTypeDefinition();
            var a = t.GetGenericArguments();
            if (def.FullName == "System.Nullable`1") return TypeName(a[0]) + "?";
            if (def.FullName != null && def.FullName.StartsWith("System.ValueTuple`"))
                return "(" + string.Join(", ", a.Select(TypeName)) + ")";
            string n = def.Name.Split('`')[0];
            if (t.IsNested && !t.IsGenericTypeDefinition) n = def.DeclaringType.Name + "." + n;
            return n + "<" + string.Join(", ", a.Select(TypeName)) + ">";
        }
        return t.IsNested ? t.DeclaringType.Name + "." + t.Name : t.Name;
    }

    static string ParamList(ParameterInfo[] ps) => string.Join(", ", ps.Select(p =>
    {
        string s = (p.GetCustomAttributesData().Any(a => a.AttributeType.Name == "ParamArrayAttribute") ? "params " : "")
                   + TypeName(p.ParameterType) + " " + p.Name;
        if (p.HasDefaultValue) s += " = " + Literal(p.RawDefaultValue);
        return s;
    }));

    static string Literal(object v) => v switch
    {
        null => "null",
        string s => "\"" + s + "\"",
        bool b => b ? "true" : "false",
        float f => f.ToString(System.Globalization.CultureInfo.InvariantCulture) + "f",
        double d => d.ToString(System.Globalization.CultureInfo.InvariantCulture),
        _ => Convert.ToString(v, System.Globalization.CultureInfo.InvariantCulture),
    };

    // ------------------------------------------------------------------ XML doc ids

    static string Id(Type t) => "T:" + DocName(t);

    static string DocName(Type t) => (t.FullName ?? t.Name).Replace('+', '.');

    static string Params(ParameterInfo[] ps) => ps.Length == 0 ? "" : "(" + string.Join(",", ps.Select(p => DocType(p.ParameterType))) + ")";

    static string DocType(Type t)
    {
        if (t.IsByRef) return DocType(t.GetElementType()) + "@";
        if (t.IsArray) return DocType(t.GetElementType()) + "[]";
        if (t.IsGenericParameter) return "`" + t.GenericParameterPosition;
        if (t.IsGenericType)
        {
            var def = t.GetGenericTypeDefinition();
            string n = (def.FullName ?? def.Name).Replace('+', '.');
            n = n.Substring(0, n.IndexOf('`'));
            return n + "{" + string.Join(",", t.GetGenericArguments().Select(DocType)) + "}";
        }
        return (t.FullName ?? t.Name).Replace('+', '.');
    }
}
